# Generated by Django 2.2.7 on 2019-11-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cpu',
            table='sd_cpu',
        ),
    ]
